apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
  labels:
    app: federated-cluster
spec:
  template:
    metadata:
      name: coredns
      labels:
        app: federated-cluster
        module: federation-dns-server
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v2.3.3
        command:
          - /etcd
          - --data-dir
          - /var/etcd/data
          - --listen-client-urls
          - http://0.0.0.0:2379
          - --advertise-client-urls
          - http://127.0.0.1:2379
        ports:
        - containerPort: 2379
          name: etcd
      - name: coredns
        image: coredns/coredns:005
        args:
        - -conf
        - /tmp/dns-config/Corefile
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        volumeMounts:
        - name: config-volume
          mountPath: /tmp/dns-config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: coredns-config
