---
apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: kube-system
  labels:
    app: federated-cluster
spec:
  type: NodePort
  selector:
    app: federated-cluster
    module: federation-dns-server
  ports:
    - name: dns
      protocol: UDP
      port: 53
